// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using test3.Adapter;
using UIKit;

namespace test3
{
	public partial class BooksTableViewController : UITableViewController
	{
	
		public BooksTableViewController (IntPtr handle) : base (handle)
		{

		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
		}

		public override void ViewDidAppear(bool animated)
		{
			base.ViewDidAppear(animated);

			BookTableView.Source = new BookTableViewAdapter();
			BookTableView.RowHeight = UITableView.AutomaticDimension;
			BookTableView.ReloadData();
		}


        public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
        {
            base.PrepareForSegue(segue, sender);
			if (segue.Identifier == "showBookControllerSegue")
            {
				var navController = segue.DestinationViewController as EditBookViewController;
                if (navController != null)
                {
					var source = BookTableView.Source as BookTableViewAdapter;
					var rowPath = BookTableView.IndexPathForSelectedRow;
					var item = source.GetItem(rowPath.Row);
					navController.SetTask(this, item);
                }

            }
        }

    }

	
}
