// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace test3.Views
{
	public partial class MainNavigationController : UINavigationController
	{
		public MainNavigationController (IntPtr handle) : base (handle)
		{
		}
	}
}
